import thumb0 from "../../public/projects/oppo/OPPO_Packshots_Treppe_01_NakarinFoto_Web.jpg";
import thumb1 from "../../public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_12.jpg";
import thumb2 from "../../public/projects/dosenbach/90_Dosenbach_Store_Genf__Nakarin_Foto__09_Web.jpg";
import thumb3 from "../../public/projects/stadt_adliswil/91_Kindergarten_Werd_Aussen__Nakarin_Foto__149_web.jpg";
import thumb4 from "../../public/projects/stadt_schlieren/Schlieren_Wakkerpreis_Drohne__Studio-Gataric__014_Web.jpg";
import thumb5 from "../../public/projects/VFG_burning_season/VFG_Burning_Web_Nakarin_Fotografie_04.jpg";
import thumb6 from "../../public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_01.jpg";
import thumb7 from "../../public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_03.jpg";
import thumb8 from "../../public/projects/tremondi_quinten/Quinten_Whg2OG__Nakarin-Fotografie__130_Web.jpg";

// const thumbs = [
//   thumb0,
//   thumb1,
//   thumb2,
//   thumb3,
//   thumb4,
//   thumb5,
//   thumb6,
//   thumb7,
//   thumb8,
// ];

const projectData = [
  {
    index: 0,
    name: "OPPO",
    description: "n/a",
    location: "Zürich",
    thumbnailPath: "OPPO_Packshots_Treppe_01_NakarinFoto_Web.jpg",
    thumbnail: thumb0,
    yearStart: "2020",
    yearEnd: "laufend",
    client: "OPPO",
    role: "Fotograf",
    link: "",
    images: [
      "/public/projects/oppo/70_OPPO_Enco_X__01_web.jpg",
      "/public/projects/oppo/70_OPPO_Enco_X__03_web.jpg",
      "/public/projects/oppo/70_OPPO_Winter_After_Xmas__01_web.jpg",
      "/public/projects/oppo/70_OPPO_Winter_Braunwald__01_web.jpg",
      "/public/projects/oppo/Experience_Lang_Final_1080.mp4",
      "/public/projects/oppo/OPPO_Packshots__03_NakarinFoto_Web.jpg",
      "/public/projects/oppo/OPPO_Packshots_Treppe_01_NakarinFoto_Web.jpg",
      "/public/projects/oppo/OPPO_Reno_Find_X_Sep__07_LowRes_NakarinFoto_Web.jpg",
      "/public/projects/oppo/OPPO_Reno_Find_X_Sep__17_LowRes_NakarinFoto_Web.jpg",
      "/public/projects/oppo/OPPO_Reno_Find_X_Sep__20_LowRes_NakarinFoto_Web.jpg",
      "/public/projects/oppo/OPPO_Watch_Packshots__12_NakarinFoto_Web.jpg",
      "/public/projects/oppo/OPPO_Watch_Packshots__14_NakarinFoto_Web.jpg",
      "/public/projects/oppo/Part_2_Was_Ist_Android_Final_1080p.mp4",
      "/public/projects/oppo/Part_3_Wieso_Oppo_Final_1080p.mp4",
    ],
  },
  {
    index: 1,
    name: "Michel Freudenberg",
    description: "n/a",
    location: "Zürich",
    thumbnailPath: "Michel_Freudenberg_Nakarin_Fotografie_12.jpg",
    thumbnail: thumb1,
    yearStart: "2019",
    yearEnd: "2019",
    client: "Michel Freudenberg",
    role: "Fotograf",
    link: "",
    images: [
      "/public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_03.jpg",
      "/public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_05.jpg",
      "/public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_07.jpg",
      "/public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_08.jpg",
      "/public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_09.jpg",
      "/public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_10.jpg",
      "/public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_12.jpg",
      "/public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_13.jpg",
      "/public/projects/michel_freudenberg/Michel_Freudenberg_Nakarin_Fotografie_14.jpg",
    ],
  },
  {
    index: 2,
    name: "Dosenbach",
    description: "n/a",
    location: "Genf",
    thumbnailPath: "90_Dosenbach_Store_Genf__Nakarin_Foto__09_Web.jpg",
    thumbnail: thumb2,
    yearStart: "2021",
    yearEnd: "2021",
    client: "Dosenbach",
    role: "Fotograf",
    link: "",
    images: [
      "/public/projects/dosenbach/90_Dosenbach_Store_Genf__Nakarin_Foto__04_Web.jpg",
      "/public/projects/dosenbach/90_Dosenbach_Store_Genf__Nakarin_Foto__05_Web.jpg",
      "/public/projects/dosenbach/90_Dosenbach_Store_Genf__Nakarin_Foto__09_Web.jpg",
      "/public/projects/dosenbach/90_Dosenbach_Store_Genf__Nakarin_Foto__11_Web.jpg",
      "/public/projects/dosenbach/90_Dosenbach_Store_Genf__Nakarin_Foto__16_Web.jpg",
      "/public/projects/dosenbach/90_Dosenbach_Store_Genf__Nakarin_Foto__19_Web.jpg",
      "/public/projects/dosenbach/90_Dosenbach_Store_Genf__Nakarin_Foto__21_Web.jpg",
      "/public/projects/dosenbach/90_Dosenbach_Store_Genf__Nakarin_Foto__25_Web.jpg",
    ],
  },
  {
    index: 3,
    name: "Stadt Adliswil",
    description: "n/a",
    location: "Adliswil",
    thumbnailPath: "91_Kindergarten_Werd_Aussen__Nakarin_Foto__149_web.jpg",
    thumbnail: thumb3,
    yearStart: "2020",
    yearEnd: "laufend",
    client: "Dosenbach",
    role: "Fotograf",
    link: "",
    images: [
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Aussen__Nakarin_Foto__149_web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Aussen__Nakarin_Foto__179_web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Aussen__Nakarin_Foto__197_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Aussen__Nakarin_Foto__205_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Details__Nakarin_Foto__80_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Drohne__Nakarin_Foto__232_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Eingang__Nakarin_Foto__122_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Eingang__Nakarin_Foto__129_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Raeume__Nakarin_Foto__09_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Raeume__Nakarin_Foto__45_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Raeume__Nakarin_Foto__53_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Raeume__Nakarin_Foto__66_Web.jpg",
      "/public/projects/stadt_adliswil/91_Kindergarten_Werd_Raeume__Nakarin_Foto__67_Web.jpg",
    ],
  },
  {
    index: 4,
    name: "Stadt Schlieren",
    description: "n/a",
    location: "Schlieren",
    thumbnailPath: "Schlieren_Wakkerpreis_Drohne__Studio-Gataric__014_Web.jpg",
    thumbnail: thumb4,
    yearStart: "2021",
    yearEnd: "2021",
    client: "Stadt Schlieren",
    role: "Fotograf",
    link: "",
    images: [
      "/public/projects/stadt_schlieren/AmRietp_2020_Nakarin_Foto__01_web.jpg",
      "/public/projects/stadt_schlieren/AmRietp_2020_Nakarin_Foto__02_Web.jpg",
      "/public/projects/stadt_schlieren/AmRietp_2020_Nakarin_Foto__03_web.jpg",
      "/public/projects/stadt_schlieren/AmRietp_2020_Nakarin_Foto__07_Web.jpg",
      "/public/projects/stadt_schlieren/AmRietp_2020_Nakarin_Foto__10_web.jpg",
      "/public/projects/stadt_schlieren/AmRietp_2020_Nakarin_Foto__11_web.jpg",
      "/public/projects/stadt_schlieren/Schlieren_Wakkerpreis_Drohne__Studio-Gataric__008_Web.jpg",
      "/public/projects/stadt_schlieren/Schlieren_Wakkerpreis_Drohne__Studio-Gataric__013_Web.jpg",
      "/public/projects/stadt_schlieren/Schlieren_Wakkerpreis_Drohne__Studio-Gataric__014_Web.jpg",
      "/public/projects/stadt_schlieren/Schlieren_Wakkerpreis_Drohne__Studio-Gataric__020_Web.jpg",
    ],
  },
  {
    index: 5,
    name: "VFG Burning Season",
    description: "n/a",
    location: "Chiang Mai, Thailand",
    thumbnailPath: "VFG_Burning_Web_Nakarin_Fotografie_04.jpg",
    thumbnail: thumb5,
    yearStart: "2019",
    yearEnd: "2019",
    client: "VFG Burning Season",
    role: "Fotograf",
    link: "",
    images: [
      "/public/projects/VFG_burning_season/VFG_Burning_Web_Nakarin_Fotografie_01.jpg",
      "/public/projects/VFG_burning_season/VFG_Burning_Web_Nakarin_Fotografie_02.jpg",
      "/public/projects/VFG_burning_season/VFG_Burning_Web_Nakarin_Fotografie_03.jpg",
      "/public/projects/VFG_burning_season/VFG_Burning_Web_Nakarin_Fotografie_04.jpg",
      "/public/projects/VFG_burning_season/VFG_Burning_Web_Nakarin_Fotografie_05.jpg",
      "/public/projects/VFG_burning_season/VFG_Burning_Web_Nakarin_Fotografie_06.jpg",
      "/public/projects/VFG_burning_season/VFG_Burning_Web_Nakarin_Fotografie_07.jpg",
    ],
  },
  {
    index: 6,
    name: "Panthera Onca",
    description: "n/a",
    location: "Mollis Glarus",
    thumbnailPath: "Panthera_Onca_Web_Nakarin_Fotografie_01.jpg",
    thumbnail: thumb6,
    yearStart: "2018",
    yearEnd: "2018",
    client: "Panthera Onca",
    role: "Fotograf",
    link: "",
    images: [
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_01.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_02.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_03.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_04.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_05.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_06.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_07.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_08.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_09.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_10.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_11.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_12.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_13.jpg",
      "/public/projects/panthera_onca/Panthera_Onca_Web_Nakarin_Fotografie_14.jpg",
    ],
  },
  {
    index: 7,
    name: "Take-Off Birrfeld",
    description: "n/a",
    location: "Birrfeld",
    thumbnailPath: "Birrfeld_Web_Nakarin_Fotografie_03.jpg",
    thumbnail: thumb7,
    yearStart: "2018",
    yearEnd: "2018",
    client: "Take-Off Birrfeld",
    role: "Fotograf",
    link: "",
    images: [
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_01.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_02.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_03.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_04.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_05.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_06.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_07.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_08.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_09.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_10.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_11.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_12.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_13.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_14.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_15.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_16.jpg",
      "/public/projects/takeoff_birrfeld/Birrfeld_Web_Nakarin_Fotografie_17.jpg",
    ],
  },
  {
    index: 8,
    name: "Tremondi Quinten",
    description: "n/a",
    location: "Quinten",
    thumbnailPath: "Quinten_Whg2OG__Nakarin-Fotografie__130_Web.jpg",
    thumbnail: thumb8,
    yearStart: "2020",
    yearEnd: "2020",
    client: "Tremondi Quinten",
    role: "Fotograf",
    link: "",
    images: [
      "/public/projects/tremondi_quinten/Quinten___Nakarin-Foto_01_Web.jpg",
      "/public/projects/tremondi_quinten/Quinten_Aussen_Nakarin-Foto_01_Web.jpg",
      "/public/projects/tremondi_quinten/Quinten_Whg2OG__Nakarin-Fotografie__130_Web.jpg",
      "/public/projects/tremondi_quinten/Quinten_Whg2OG__Nakarin-Fotografie__144_Web.jpg",
      "/public/projects/tremondi_quinten/Quinten_Whg2OG__Nakarin-Fotografie__172_Web.jpg",
      "/public/projects/tremondi_quinten/Quinten_Whg2OG__Nakarin-Fotografie__176_Web.jpg",
      "/public/projects/tremondi_quinten/Quinten_Whg2OG__Nakarin-Fotografie__187_Web.jpg",
      "/public/projects/tremondi_quinten/Quinten_Whg2OG__Nakarin-Fotografie__190_Web.jpg",
      "/public/projects/tremondi_quinten/Quinten_Whg2OG__Nakarin-Fotografie__191_Web.jpg",
      "/public/projects/tremondi_quinten/Quinten_Whg2OG__Nakarin-Fotografie__192_Web.jpg",
    ],
  },
];

export default projectData;
